globalvar menuID;
global.menuID = 1;
globalvar menuOpen;
global.menuOpen = 0;
globalvar questionID;
questionID = 0;
globalvar paused;
paused = 0;

globalvar questions;
questions[1] = "Who is the current president of the university?";
questions[2] = "Who was the first president of the university?";
questions[3] = "Which was the first academic building on campus?";
questions[4] = "Who was the founder of the university?";
questions[5] = "What is University Police’s phone number?";
questions[6] = "What does Clark’s former motto, “Fiat Lux” mean?";
questions[7] = "What is the name of the university’s newspaper?";
questions[8] = "What athletic division is Clark?";
questions[9] = "When did Sigmund Freud give his famous “Clark Lectures?”";
questions[10] = "The statue in Red Square is of what famous psychologist?";
questions[11] = "What year was the university founded?";
questions[12] = "Wright hall is what type of university building?";
questions[13] = "What is Clark’s Mascot?";
questions[14] = "How many Program of Liberal Studies requirements are needed to graduate??";
questions[15] = "Wright Hall has which of the following?";
questions[16] = "Bullock Hall has which of the following?";
questions[17] = "Which dormitory is Clark’s only same-sex hall?";
questions[18] = "How many undergraduate majors does Clark offer?";
questions[19] = "LEEP is an acronym for what?";
questions[20] = "What does RA stand for?";
questions[21]= "Where is the ITS Help Desk located?";
questions[22]=" What is Escort’s phone number?";
questions[23]= "What is the nickname for students of Clark University?";
questions[24]= "In 2013 what was the undergraduate percentage of men/ women?";
questions[25]="What is the average class size at Clark?";
questions[26]="What is the most popular undergraduate major?";
questions[27]="What percentage of first-year students live on campus?";
questions[28]="Does Clark require applicants to send in their SAT scores?";
questions[29]="What is the university’s student to faculty ratio?";
questions[30]="What percentage of undergraduates receive some form of financial assistance?";
questions[31] = "How many varsity sports teams are there at Clark University?"
questions[32] = "Clark University is ranked what number in the small size category of the Peace Corps list of top colleges?"
questions[33] = "What part of Worcester is Clark University located in?"
questions[34] = "Worcester is the second largest city in New England.  Which is the largest?"
questions[35] = "Who rated Clark University in the top 50 of “Best value in Private Colleges”?"
questions[36] = "During what month does Clark commencement take place?"
questions[37] = "During what month does Spree Day occur?"
questions[38] = "Clark University has a music department, true or false?"
questions[39] = "What does ESL stand for?"
questions[41] = "What was special about Clark University when it opened?";
questions[42] = "What does CMT stand for?";
questions[43] = "How many student clubs does Clark University have?";


globalvar option1;
option1[1] = "G. Stanley Hall";
option1[2] = "G. Stanley Hall";
option1[3] = "Jefferson Hall";
option1[4] = "Wallace Walter Atwood";
option1[5] = "7745";
option1[6] = "Challenge Convention";
option1[7] = "The Scarlet";
option1[8] = "Division I";
option1[9] = "1900";
option1[10] = "Sigmund Freud";
option1[11] = "1887";
option1[12] = "Dormitory";
option1[13] = "Tiger";
option1[14] = "14";
option1[15] = "Pool Table";
option1[16] = "Pool Table";
option1[17] = "Bullock";
option1[18] = "28";
option1[19] = "Learn Everything & Experience People";
option1[20] = "Resident Actor";
option1[21]="Carlson Hall";
option1[22]="7777";
option1[23]="Clark Students";
option1[24]="50% / 50%";
option1[25]="25";
option1[26]="Psychology";
option1[27]="75%";
option1[28]="Yes";
option1[29]="1:1";
option1[30]="85%";
option1[31] = "12"
option1[32] = "1"
option1[33] = "Main South"
option1[34] = "Manchester, New Hampshire"
option1[35] = "Forbes"
option1[36] = "December"
option1[37] = "February"
option1[38] = "True"
option1[39] = "College of Professional and Continuing Education"
option1[40] = "Estimated Service Life"
option1[41] = "It was the first undergraduate only college in the USA";
option1[42] = "Clark Musical Theatre";
option1[43] = "Over 9000";



globalvar option2;
option2[1] = "Edmund Sanford";
option2[2] = "Edmund Sanford";
option2[3] = "Sackler Science Center";
option2[4] = "G. Stanley Hall";
option2[5] = "7575";
option2[6] = "Let There Be Light";
option2[7] = "The Crimson";
option2[8] = "Division II";
option2[9] = "1912";
option2[10] = "Alfred Adler";
option2[11] = "1952";
option2[12] = "Academic Building";
option2[13] = "Cougar";
option2[14] = "4";
option2[15] = "Foosball Table";
option2[16] = "Foosball Table";
option2[17] = "Dodd";
option2[18] = "42";
option2[19] = "Liberal Education & Effective Practice";
option2[20] = "Room Advisor";
option2[21]="Higgins University Center";
option2[22]="7745";
option2[23]="Clarkies";
option2[24]="36% / 64%";
option2[25]="18";
option2[26]="Biology";
option2[27]="100%";
option2[28]="Maybe";
option2[29]="35:1";
option2[30]="92%";
option2[31] = "17"
option2[32] = "15"
option2[33] = "University Park"
option2[34] = "Boston, Massachusetts"
option2[35] = "USA Today"
option2[36] = "April"
option2[37] = "March"
option2[38] = "Who cares?"
option2[39] = "College of People and Caring for Everyone"
option2[40] = "Electronic System Library"
option2[41] = "It was the first graduate only college in the USA";
option2[42] = "Clark Money and Treasury";
option2[43] = "About 100";


globalvar option3;
option3[1] = "David Angel";
option3[2] = "David Angel";
option3[3] = "Estabrook Hall";
option3[4] = "Jonas Clark";
option3[5] = "7445";
option3[6] = "Change Our World";
option3[7] = "Cougar Weekly";
option3[8] = "Division III";
option3[9] = "1946";
option3[10] = "G. Stanley Hall";
option3[11] = "1886";
option3[12] = "Library";
option3[13] = "Lion";
option3[14] = "7";
option3[15] = "Swimming Pool";
option3[16] = "Swimming Pool";
option3[17] = "Dana";
option3[18] = "35";
option3[19] = "Learning Experience & Effective Practice";
option3[20] = "Resident Advisor";
option3[21]="Academic Commons at Goddard Library";
option3[22]="7575";
option3[23]="Clarkers";
option3[24]="48% / 52%";
option3[25]="40";
option3[26]="Computer Science";
option3[27]="96%";
option3[28]="Maybe Not";
option3[29]="18:1";
option3[30]="75%";
option3[31] = "4"
option3[32] = "18"
option3[33] = "Lincoln Square"
option3[34] = "Hartford, Connecticut"
option3[35] = "Kiplinger"
option3[36] = "May"
option3[37] = "April"
option3[38] = "False"
option3[39] = "College of Professional and College Education"
option3[40] = "English as a Sixth Language"
option3[41] = "It was the first college in Worcester ";
option3[42] = "Clark Means Trouble";
option3[43] = "About 78";


globalvar option4;
option4[1] = "Richard Traina";
option4[2] = "Richard Traina";
option4[3] = "Jonas Clark Hall";
option4[4] = "David Angel";
option4[5] = "7755";
option4[6] = "See the Light";
option4[7] = "The Beacon";
option4[8] = "Division IV";
option4[9] = "1909";
option4[10] = "John Dewey";
option4[11] = "1910";
option4[12] = "Administrative Building";
option4[13] = "Jaguar";
option4[14] = "8";
option4[15] = "Poker Table";
option4[16] = "Poker Table";
option4[17] = "Maywood";
option4[18] = "32";
option4[19] = "Looking Everywhere & Eating Pie";
option4[20] = "Real Actor";
option4[21]= "151 Woodland Street";
option4[22] = "7566";
option4[23]="Cougars";
option4[24]="42% / 58%";
option4[25]="21";
option4[26]="Political Science";
option4[27]="87%";
option4[28]="No";
option4[29]="10:1";
option4[30]="100%";
option4[31] = "8"
option4[32] = "25"
option4[33] = "Union Hill"
option4[34] = "Burlington, Vermont"
option4[35] = "The Wall Street Journal"
option4[36] = "June"
option4[37] = "May"
option4[38] = "Maybe"
option4[39] = "Citizen Outreach and Political Action Committee Event"
option4[40] = "English as a Second Language"
option4[41] = "It was the first college in the USA to have a psychology program ";
option4[42] = "Clark Makes Truffles";
option4[43] = "About 130";


globalvar solution;
solution[1] = "3";
solution[2] = "1";
solution[3] = "4";
solution[4] = "3";
solution[5] = "2";
solution[6] = "2";
solution[7] = "1";
solution[8] = "3";
solution[9] = "4";
solution[10] = "1";
solution[11] = "1";
solution[12] = "1";
solution[13] = "2";
solution[14] = "4";
solution[15] = "1";
solution[16] = "1";
solution[17] = "2";
solution[18] = "4";
solution[19] = "2";
solution[20] = "3";
solution[21] = "3";
solution[22] = "1";
solution[23] = "2";
solution[24] = "4";
solution[25] = "4";
solution[26] = "1";
solution[27] = "3";
solution[28] = "4";
solution[29] = "4";
solution[30] = "1";
solution[31] = "2";
solution[32] = "3";
solution[33] = "1";
solution[34] = "2";
solution[35] = "3";
solution[36] = "3";
solution[37] = "3";
solution[38] = "1";
solution[39] = "1";
solution[40] = "4";
solution[41] = "2";
solution[42] = "1";
solution[43] = "4";
